# Generated by Django 4.2.2 on 2023-06-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ratting',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productfood',
            name='ratting',
            field=models.IntegerField(default=0),
        ),
    ]
